### ISSUE TITLE
Plugin doesn't support NodeBB Version 1.7.3

### ISSUE THREAD

**Issue by x1nf1** [joe1chen/nodebb-plugin-search-elasticsearch#12]
Hi @joe1chen 
Thanks for the plugin 🙏 . But unfortunately the plugin doesn't work with NodeBB version 1.7.2 and 1.7.3 .

**Comment by fbennett** [comment]
Here too. The plugin crashed the nodebb process, and `nodebb` would not run until the plugin was disabled from the command line:
```
./nodebb reset -p nodebb-plugin-search-elasticsearch
```
